services:
  - type: web
    name: pagadiarios-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PGUSER
        value: neondb_owner
      - key: PGPASSWORD
        value: npg_GBk8EJM7TdfO
      - key: PGHOST
        value: ep-royal-sun-a4kntl0s-pooler.us-east-1.aws.neon.tech
      - key: PGDATABASE
        value: neondb
      - key: PGPORT
        value: 5432
      - key: PGSSLMODE
        value: require
  - type: static
    name: pagadiarios-frontend
    staticPublishPath: frontend
